### ISSUE TITLE
Will only work on newest Meteor when MongoDB is installed

### ISSUE THREAD

**Issue by hbokh** [peperzaken/jeeves#3]
```
# mrt

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

[[[[[ /vagrant/jeeves ]]]]]

=> Started proxy.
=> Meteor 1.1.0.2 is available. Update this project with 'meteor update'.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Can't start Mongo server.
npm-container: updating npm dependencies -- restify, request...

/usr/local/lib/node_modules/meteorite/lib/command.js:41
            throw "Command exited with " + code + "/" + signal;
                                                      ^
Command exited with 254/null
```

See http://stackoverflow.com/a/18546761/615962

But the only way to get things up on port 3000 was to install mongodb and run
   `MONGO_URL=mongodb://localhost mrt`

**Comment by dstollie** [comment]
@hbokh meteorite is not longer maintained and the functionality it came with is now availble in meteor itself! Refer to https://www.meteor.com/install and update yourself to the latest meteor version (meteor update might work aswell)

Whenever ur updated stop using the command 'mrt' but instead use 'meteor'. This should start the mongo database automatically. Be sure whenever you start meteor no external database on port 3001 is running.

p.s. Im dutch so if you are to, we better communicate in dutch ;p

**Comment by hbokh** [comment]
Thanks, I will try.
Please let @zout update the README to replace `mrt` with `meteor`.
I'll communicate in English, since the whole project is. Maar toch bedankt!

**Comment by RubenHoms** [comment]
+1 the project was initially written when meteorite was something that enhanced functionality. Now that the same functionality, mainly packages, is ported into the actual Meteor codebase you should run the project with `meteor`.

I'll try to update the documentation today to reflect the current state of things. Thanks for being watchful!

**Comment by hbokh** [comment]
Thanks, Ruben.
Don't forget to test things too, besides editing the docs: I had numerous errors about the location of Druppel, even after being changed and I couldn't get beyond the spinner on the dashboard.
Could be `mrt`-related. If these errors remain, I probably file a new issue.

**Comment by RubenHoms** [comment]
@hbokh I had some issues while installing the packages but fixed it by running `sudo meteor` because NPM needed root privileges to install them. Further, after adding the slides to the system by going to the administration system at `http://localhost:3000/admin` everything worked fine for me! If you still have issues please do file a new one! :+1:

**Comment by hbokh** [comment]
Please reopen the issue, because even when using `meteor` instead of `mrt` the outcome is the same: the MongoDB-issue remains.
To reproduce: I use a clean Vagrantbox (trusty64 - (virtualbox, 20150427.0.0)), update to `Meteor 1.1.0.2` and a fresh clone of jeeves.
Only added extra's on the box are packages nodejs and nodejs-legacy.

```
root@vagrant-ubuntu-trusty-64:/vagrant/jeeves# pwd
/vagrant/jeeves

root@vagrant-ubuntu-trusty-64:/vagrant/jeeves# meteor
[[[[[ /vagrant/jeeves ]]]]]

=> Started proxy.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Can't start Mongo server.
```

So basically, you **NEED** a MongoDB installed and running:

```
root@vagrant-ubuntu-trusty-64:/vagrant/jeeves# aptitude install mongodb

root@vagrant-ubuntu-trusty-64:/vagrant/jeeves# meteor
[[[[[ /vagrant/jeeves ]]]]]

=> Started proxy.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Unexpected mongo exit code 1. Restarting.
Can't start Mongo server.

root@vagrant-ubuntu-trusty-64:/vagrant/jeeves# service mongodb status
mongodb start/running, process 4055

root@vagrant-ubuntu-trusty-64:/vagrant/jeeves# MONGO_URL=mongodb://localhost meteor
[[[[[ /vagrant/jeeves ]]]]]

=> Started proxy.
I20150508-10:54:29.952(0)? warn: You're still using the default location settings for the druppel slide, to change this behaviour set your own values in server/slides/druppel/source.js
I20150508-10:54:30.229(0)? info: Created superuser 'admin' with password 'admin'.
=> Started your app.

=> App running at: http://localhost:3000/
I20150508-10:54:56.173(0)? info: Screen "vagrant" (all) added.
```

**Comment by RubenHoms** [comment]
@hbokh You're correct. I reproduced your problem by doing as you said, booting up a clean trusty64 vagrant instance and running the project clean.

I fixed this by running `export LC_ALL=C` before running `meteor`. I'm not sure why this helps, but found the solution [on this stackoverflow post](http://stackoverflow.com/a/25253388/1106611). Some googling later I found out that the LC_ALL flag determines the values for all locale categories, which only makes less sense but points to it being some underlying VM problem in my opinion.

I found [some](https://github.com/meteor/meteor/issues/1064) old [meteor](https://github.com/meteor/meteor/issues/4318) issues which point to the same problem as probably being one with vagrant, thus probably explaining why this happened in this scenario.

I'm leaving this issue closed seeing as this is a VM specific issue. When I remove meteor from my own system (Ubuntu 14.04, 64 bit), reinstall it and run the project there seems to be no issues.

**Comment by hbokh** [comment]
Thank you, Ruben. Reading al that on SO makes more sense: I ran jeeves from /vagrant/jeeves which is a shared folder that's on my Mac. Moving the jeeves-folder into /opt within Vagrant, doing a `meteor reset` made it work out of the box afterwards.
Indeed a VM specific issue... Bedankt en een prettig weekend!
