### ISSUE TITLE
Keeps hanging on 'Welcome to Jeeves, your slides will be served shortly.'

### ISSUE THREAD

**Issue by jeffhuys** [peperzaken/jeeves#5]
I've followed all instructions, and got it running without a problem. Well, the only problem I have is that it keeps showing 'Welcome to Jeeves, your slides will be served shortly.'. I've tried adding a slide of my own using your CLI tool, but it doesn't help. Any ideas?

**Comment by RubenHoms** [comment]
First off, thanks for giving Jeeves a try! Besides adding a slide of your own with the CLI tool have you also added it to the scheduler through the admin interface at `/admin`?
If not, this is the reason why. Jeeves will show you slides at the times you set them to be shown on. For example you can display them 24/7 but can also only show them for example on fridays between 4-5 o'clock.

**Comment by jeffhuys** [comment]
Doh! That works! Awesome, thank you so much for the fast and accurate response. I will be sharing this repo amongst my friends, it deserves a lot more recognition. I will be working on getting a screen up at my office, I really like the system. Thank you again!

Je bent geweldig :smile:
